// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfgjccuvsggfrxwharkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZ2pjY3V2c2dnZnJ4d2hhcmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTg2NzgsImV4cCI6MjA2MTc3NDY3OH0.7C7nV9HQ55OrVl0yNH7SpGnlLj3lY-s9edZ6aoMMDXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);