
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfgjccuvsggfrxwharkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmZ2pjY3V2c2dnZnJ4d2hhcmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTg2NzgsImV4cCI6MjA2MTc3NDY3OH0.7C7nV9HQ55OrVl0yNH7SpGnlLj3lY-s9edZ6aoMMDXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a helper function to reset credit note counter for a specific financial year
export const resetCreditNoteCounter = async (companyId: string, financialYear: string) => {
  try {
    const { data, error } = await supabase
      .from('company_settings')
      .update({
        credit_note_counter: 1,
        updated_at: new Date().toISOString() // Fix: Convert Date to ISO string
      })
      .eq('company_id', companyId)
      .eq('current_financial_year', financialYear);
    
    if (error) throw error;
    return { success: true, data };
  } catch (error) {
    console.error("Error resetting credit note counter:", error);
    return { success: false, error };
  }
};
